/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_studiohartman_jamepad_ControllerIndex */

#ifndef _Included_com_studiohartman_jamepad_ControllerIndex
#define _Included_com_studiohartman_jamepad_ControllerIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_studiohartman_jamepad_ControllerIndex
 * Method:    nativeConnectController
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_studiohartman_jamepad_ControllerIndex_nativeConnectController
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_studiohartman_jamepad_ControllerIndex
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_studiohartman_jamepad_ControllerIndex_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_studiohartman_jamepad_ControllerIndex
 * Method:    nativeIsConnected
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_studiohartman_jamepad_ControllerIndex_nativeIsConnected
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_studiohartman_jamepad_ControllerIndex
 * Method:    nativeDoVibration
 * Signature: (JIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_studiohartman_jamepad_ControllerIndex_nativeDoVibration
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     com_studiohartman_jamepad_ControllerIndex
 * Method:    nativeCheckButton
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_studiohartman_jamepad_ControllerIndex_nativeCheckButton
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_studiohartman_jamepad_ControllerIndex
 * Method:    nativeCheckAxis
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_studiohartman_jamepad_ControllerIndex_nativeCheckAxis
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_studiohartman_jamepad_ControllerIndex
 * Method:    nativeGetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_studiohartman_jamepad_ControllerIndex_nativeGetName
  (JNIEnv *, jobject, jlong);
  
  /*
 * Class:     com_studiohartman_jamepad_ControllerManager
 * Method:    nativeInitSDLGamepad
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_studiohartman_jamepad_ControllerManager_nativeInitSDLGamepad
  (JNIEnv *, jobject);

/*
 * Class:     com_studiohartman_jamepad_ControllerManager
 * Method:    nativeControllerConnectedOrDisconnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_studiohartman_jamepad_ControllerManager_nativeControllerConnectedOrDisconnected
  (JNIEnv *, jobject);

/*
 * Class:     com_studiohartman_jamepad_ControllerManager
 * Method:    nativeAddMappingsFromFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_studiohartman_jamepad_ControllerManager_nativeAddMappingsFromFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
